### Filter by txt
get http://127.0.0.1:3030/api/bug?txt=g

### Filter by txt & minSeverity

get http://127.0.0.1:3030/api/bug?txt=g&minSeverity=3

### Sort by title

get http://127.0.0.1:3030/api/bug?sortField=title

### Sort by title descending

get http://127.0.0.1:3030/api/bug?sortField=title&sortDir=-1

### Get first page with page size=2

get http://127.0.0.1:3030/api/bug?pageIdx=0&pageSize=2

### Get first page with default page size

get http://127.0.0.1:3030/api/bug?pageIdx=0